language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install django coveralls

before_script:
  - django-admin startproject django_pj
  - cp -r pay_ir django_pj/
  - cp travis_* django_pj/django_pj/

script:
  - coverage run --source=pay_ir django_pj/manage.py test --settings="django_pj.travis_settings"

after_success:
- coveralls